#!/usr/bin/env bash

# Check if this is the initial commit
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Use git diff-index to check for whitespace errors
NEW_FILES=$(git --no-pager diff --name-only --cached)
NEW_FILES_NO_SNAPSHOTS=$(echo "$NEW_FILES" | { grep -v js.snap || true; })

# Exit early if there is no file
if [ -z $NEW_FILES_NO_SNAPSHOTS ];
then
    exit 0
fi

if ! git diff-index --check $against -- NEW_FILES_NO_SNAPSHOTS
then
    echo "Aborting commit due to whitespace errors."
    exit 1
else
    # Fail on first line that fails.
    set -e

    JS_FILES=$(echo "$NEW_FILES_NO_SNAPSHOTS" | { grep client/js || true; })
    SASS_FILES=$(echo "$NEW_FILES_NO_SNAPSHOTS" | { grep client/scss || true; })

    if [ -n "$JS_FILES" ];
    then
        npm run linter:js -s -- $JS_FILES
    fi
fi
