options:
  formatter: stylish
files:
  include: 'client/scss/**/*.scss'
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 0

  # Disallows
  no-color-keywords: 1
  no-color-literals: 1
  no-css-comments: 1
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 2
  no-ids: 2
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 0
  no-misspelled-properties: 0
  no-qualifying-elements:
    - 0
    - allow_element_with_attribute: false
      allow_element_with_class: false
      allow_element_with_id: false
  no-trailing-zero: 1
  no-transition-all: 1
  no-url-protocols: 1
  no-vendor-prefixes: 0
  no-warn: 0
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    - 1
    - convention: hyphenatedbem
      allow-leading-underscore: true
      ignore:
        - js_class
  function-name-format:
    - 1
    - convention: hyphenatedlowercase
      allow-leading-underscore: true
      ignore:
        - js_class
  id-name-format:
    - 1
    - convention: hyphenatedbem
      allow-leading-underscore: true
      ignore:
        - js_class
  mixin-name-format:
    - 1
    - convention: hyphenatedlowercase
      allow-leading-underscore: true
      ignore:
        - js_class
  placeholder-name-format:
    - 1
    - convention: hyphenatedlowercase
      allow-leading-underscore: true
      ignore:
        - js_class
  variable-name-format:
    - 1
    - convention: hyphenatedlowercase
      allow-leading-underscore: true
      ignore:
        - js_class

  # Style Guide
  bem-depth: 0
  border-zero: 1
  brace-style: 1
  clean-import-paths: 0
  empty-args: 1
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  indentation:
    - 0
    - size: 4
  leading-zero:
    - 1
    - style: exclude_zero
  nesting-depth:
    - 1
    - max-depth: 3
  property-sort-order:
    - 1
    - ignore_unspecified: true
      order:
        - display
        - position
  quotes: 1
  shorthand-values: 1
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace:
    - 1
    - allow_single_line_padding: true
      style: space
  space-before-bang: 1
  space-after-bang: 0
  space-between-parens: 1
  space-around-operator: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
